apiVersion: apps/v1
kind: Deployment
metadata:
  name: forms-backend
  namespace: forms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forms-backend
  template:
    metadata:
      labels:
        app: forms-backend
    spec:
      containers:
        - name: forms-backend
          image: ghcr.io/python-discord/forms-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: forms-backend-env
