name: Bug Report
description: "Something isn't working as expected"
labels: ["type: bug", triage]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Other developers need to be able to reproduce your bug reports to fix them,
        so please fill the following form to the best of your abilities.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief overview of what the bug is
      placeholder: Clicking the submit button wipes my harddrive.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: A set of steps that an engineer can take to find and recreate this bug
      placeholder: |
        1. Create a new form
        2. Submit an empty response
        3. ...
    validations:
      required: true
  - type: textarea
    id: files
    attributes:
      label: Files
      description: If you have any screenshots, log files, or other files that you believe are relevant, you can attach them here
    validations:
      required: false
  - type: textarea
    id: technical
    attributes:
      label: Technical Details
      description: "If you have a technical overview of what is causing the bug please describe it here, don't worry if not"
    validations:
      required: false
