"""
Link form questions to forms.

Revision ID: bef2f206168e
Revises: 787116206e6d
Create Date: 2024-07-21 12:14:55.545648+00:00
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bef2f206168e"
down_revision = "787116206e6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form_questions", sa.Column("form_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("form_questions_form_id_forms_fk"), "form_questions", "forms", ["form_id"], ["form_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("form_questions_form_id_forms_fk"), "form_questions", type_="foreignkey"
    )
    op.drop_column("form_questions", "form_id")
    # ### end Alembic commands ###
