"""
Add form responses.

Revision ID: 9ee599d0f323
Revises: bef2f206168e
Create Date: 2024-07-21 12:40:20.326205+00:00
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ee599d0f323"
down_revision = "bef2f206168e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_responses",
        sa.Column("response_id", sa.Integer(), nullable=False),
        sa.Column("form_id", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("user_email", sa.Text(), nullable=True),
        sa.Column("user_is_admin", sa.Boolean(), nullable=False),
        sa.Column("antispam_ip_hash", sa.Text(), nullable=True),
        sa.Column("antispam_user_agent_hash", sa.Text(), nullable=True),
        sa.Column("antispam_captcha_pass", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["form_id"], ["forms.form_id"], name=op.f("form_responses_form_id_forms_fk")
        ),
        sa.PrimaryKeyConstraint("response_id", name=op.f("form_responses_pk")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("form_responses")
    # ### end Alembic commands ###
